# Обусловленность системы линейных алгебраических уравнений

## Маршалкин Никита

In [ ]:
class matrix:
    def __init__(self, )

In [36]:
import numpy as np
from numpy import linalg as LA

Рассмотрим исходную систему $Ax = b$

In [17]:
A = np.matrix([[1.00, 0.99], [0.99, 0.98]])
A

matrix([[ 1.  ,  0.99],
        [ 0.99,  0.98]])

In [19]:
b = np.array([1.99, 1.97])
b

array([ 1.99,  1.97])

и систему с возмущенной правой частью $Ax' = (b + \Delta b)$

In [20]:
db = np.array([-0.000097, 0.000106])
db

array([ -9.70000000e-05,   1.06000000e-04])

Векторы неизвестных:

In [11]:
x = np.array([1, 1])
x

array([1, 1])

In [21]:
x_prime = np.array([3.0000,  -1.0203])
x_prime

array([ 3.    , -1.0203])

Векторы невязки:

In [23]:
r = A.dot(x) - b
r

matrix([[ 0.,  0.]])

In [28]:
r_prime = A.dot(x_prime) - (b + db)
r_prime

matrix([[ 0.,  0.]])


Фактическая относительная погрешность:

In [34]:
dx = LA.norm(x - x_prime) / LA.norm(x)
dx

2.0101756254118692

Число обусловленности:

In [38]:
LA.inv(A)

matrix([[-9800.,  9900.],
        [ 9900., -10000.]])